ligershark/WebOptimizer

- src/WebOptimizer.Core/Extensions/ApplicationBuilderExtensions.cs
This is to allow method chaining in `Startup.Confgure` while maintaining consistency with other `IApplicationBuilder` extension methods
> Fixes #56 - Change return type of ApplicationBuilder.UseWebOptimizer

- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
In addition to this issues addressed, this does not write out partial scss files ("_*.scss") when the option is selected.  I found that to properly compile partials I had to include them explicitly in the bundle, or subsequent changes would not be picked up in the main file.
> Fix a couple of issues related to the enableTagHelperBundling = false option

- README.md
I expanded the documentation on Tag Helpers, adding in markup so that users don't have the same questions as me when first working with them.
> Expanded the documentation on Tag Helpers

- sample2/WebOptimizer.Core.Sample2/appsettings.json
- src/WebOptimizer.Core/Asset.cs
PR #79 breaks dynamic configuration - just check example WebOptimizer.Core.Sample2
All tests passes.
In loop from Asset.cs line 92 I have replaced
```
var matcher = new Matcher();
matcher.AddInclude(outSourceFile);
...
files.AddRange(fileMatches.Where(f => !files.Contains(f)));
```
by
```
var matcher = new Matcher();
matcher.AddInclude(outSourceFile);
...
if (!files.Contains(sourceFile))
{
files.Add(sourceFile);
}
```
because paths 'outSourceFile'  and 'sourceFile' can be different 
Matcher is created for every single file check and following condition  ensures that one file that is added match
```
if (!fileMatches.Any())
{
throw new FileNotFoundException($"No files found matching \"{sourceFile}\" exist in \{dir.FullName}\"");
}
```
Following condition prevents duplicates:
```
if …
```
> DynamicConfiguration broken in PR #79

- sample/appsettings.json
- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
When enableTagHelperBundling is false, the tag helper has a conflict with single non-bundled assets. 
To repro, use the updated appsettings.json file (included in this pull request just for repro purposes) to set enableTagHelperBundling to false, and run the WebOptimizer.Core.Sample project. You will see that the Bundle page still works, but the Minification page has broken links to /js/plus.js and /css/a.css.
Expected:
```
<link href="/css/a.css?v=IuRW_uAjSlnLm_ENcFS6O-8R-2AwMZU03mWcB-b4Pf4" rel="stylesheet" />
<script src="/js/plus.js?v=oOwSxme2AgHg0Oy9TD_ZLNzn9OjP3GTCatfkeQW7CGQ" ></script>
```
Actual:
```
<link href="http://css/a.css?v=IuRW_uAjSlnLm_ENcFS6O-8R-2AwMZU03mWcB-b4Pf4" rel="stylesheet" />
<script src="http://js/plus.js?v=oOwSxme2AgHg0Oy9TD_ZLNzn9OjP3GTCatfkeQW7CGQ" …
```
> Fixed URL Error When enableTagHelperBundling == false

- src/WebOptimizer.Core/Taghelpers/BaseTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/LinkInlineHrefTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptInlineSrcTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
I was running into a memory leak. Using dotMemory and disabling things one at a time, I narrowed the problem down to WebOptimizer, then the tag helpers in WebOptimizer, and finally down to the Options parameter.
Switching the options parameter to `IOptionsMonitor` rather than `IOptionsSnapshot` fixed the memory leak. The nature of the memory leak was that each request would leak the view object, viewmodel, controller, and some ASP.NET MVC Core objects relating to the request.
I'm not sure why this was causing the memory leak.
> Switched to IOptionsMonitor due to memory leaks

- src/WebOptimizer.Core/Processors/CssFingerprinter.cs
- src/WebOptimizer.Core/Processors/RelativePathAdjuster.cs
- test/WebOptimizer.Core.Test/Processors/RelativePathAdjusterTest.cs
Instead of getting a non existing file info for generating an absolute output path, generate the absolute output path using env.WebRootPath + config.Asset.Route.
Full explanation here: 
https://github.com/ligershark/WebOptimizer/issues/109#issuecomment-621709321
The problem can easily be reproduced by adding a reference to a RCL to the AspNetCore project and then attempting add a css/scss bundle to the WebOptimizer pipeline.
> Fixed RelativePathAdjuster when WebRootFileProvider is a CompositeFileProvider

- src/WebOptimizer.Core/Processors/EnforceFileExtensions.cs
Currently the Enforcement of File Extensions from external sources is failing to register valid pipeline file extensions.
> Fix bug in the EnforceFileExtensions File

- src/WebOptimizer.Core/Processors/RelativePathAdjuster.cs
- test/WebOptimizer.Core.Test/Processors/RelativePathAdjusterTest.cs
All bundle paths seem to end up starting with a "/" which is absolute as far as Path.Combine is concerned. When combining with wwwroot the full path gets lost and the incorrect url gets generated. Removing the '/' at the start of the asset fixes this issue
May address #77, definately addresses a similar issue I have
> Fix relative path url generation

- src/WebOptimizer.Core/AssetMiddleware.cs
- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
fix the issue  #73  getting the PathBase (virtual dir) from httpContext and remove it from "route" parameter at IAssetPipeline.TryGetAssetFromRoute method  on LinkTagHelper.cs, ScriptTagHelper.cs and AssetMiddleware.cs files.
> fix issue #73, virtual dir bug on IIS

- src/WebOptimizer.Core/AssetPipeline.cs
- test/WebOptimizer.Core.Test/AssetPipelineTest.cs
- test/WebOptimizer.Core.Test/Processors/CssMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/HtmlMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/JavaScriptMinifierTest.cs
Currently WebOptimizer transforms all affected by minification/compilation/bundling urls from relative to absolute. As result it breaks page loading if it should be accessed not only from root context.
> Relative links supports

- README.md
- src/WebOptimizer.Core/AssetBuilder.cs
- src/WebOptimizer.Core/IWebOptimizerOptions.cs
- src/WebOptimizer.Core/WebOptimizerConfig.cs
- src/WebOptimizer.Core/WebOptimizerOptions.cs
in some cases, the source files used to generate the bundle just don't contain any content(maybe just comments). Currently, web optimizer would throw 404 exception, add this option for people who want to avoid ugly js errors in browser console log
> add option to allow generating bundle with empty content

- src/WebOptimizer.Core/Processors/RelativePathAdjuster.cs
Fixes RelativePathAdjuster logic when the file is in different project/Nuget and that uses static web assets. Issue #131
> RelativePathAdjuster creates wrong relative urls when references project uses static web assets

- src/WebOptimizer.Core/AssetPipeline.cs
- test/WebOptimizer.Core.Test/AssetBuilderTest.cs
- test/WebOptimizer.Core.Test/AssetMiddlewareTest.cs
- test/WebOptimizer.Core.Test/AssetPipelineTest.cs
fixes #66
Because HTTP server can accept multiple requests at the same time we can end up iterating assets concurrently and causing `System.InvalidOperationException: Collection was modified; enumeration operation may not execute.` and it's probably also possible to create invalid state (duplicates).
Switching to `ConcurrentDictionary` which protects from concurrent writes and also adds indexer to get route directly.
> Fix concurrency issue when registering assets in AssetPipeline

- src/WebOptimizer.Core/AssetMiddleware.cs
- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
Fixed incorrect usage of TrimStart-method which resulted in wrong paths to resources in certain situations. For example if PathBase was "/someapp" and you tried to serve asset from "/somepath/site.css" the wrong usage of TrimStart resulted to string "th/site.css" since it removed all characters (Value.ToCharArray()) that existed in PathBase.
> Incorrect usage of TrimStart-method generating wrong paths when PathBase exists

- sample2/WebOptimizer.Core.Sample2/Properties/launchSettings.json
- sample2/WebOptimizer.Core.Sample2/Startup.cs
- src/WebOptimizer.Core/AssetMiddleware.cs
- src/WebOptimizer.Core/IWebOptimizerOptions.cs
- src/WebOptimizer.Core/WebOptimizerOptions.cs
- test/WebOptimizer.Core.Test/AssetMiddlewareTest.cs
When serving static files the `StaticFileMiddleware` sets HTTPS compression allowed by default as it's static content and not affected of CRIME/BREACH attacks which rely on attacker modifying returned payload. As `AssetMiddleware` basically can be compared to `StaticFileMiddleware`it makes sense to allow the same logic for response compression.
I've adapted the approach `StaticFileMiddleware` uses and now also WebOptimizer content is compressed when served via HTTPS. The configuration option defaults and is documented the same way as `StaticFileMiddleware` version.
> Support compression of returned content when served via HTTPS 

- README.md
Some lines where duplicated and inserted at an incorrect spot in the README. I removed them.
> Remove duplicate lines in README

- src/WebOptimizer.Core/AssetBuilder.cs
- src/WebOptimizer.Core/Extensions/LoggerExtensions.cs
- test/WebOptimizer.Core.Test/AssetBuilderTest.cs
This fixes #102
Added FileNotFound exception handling (originally reported in #102) to pass execution to next middleware. Tested locally and can see 404 coming back
> Handling non-existent static content files

- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
Fixes #197 as the previous `HasValue` was a full check, but not Value might not be null but might be an empty string thus passing the condition and failing on the href condition check.  This simply checks if either null or empty string, getting back to the 'null' behavior.
> Fix for #197

- src/WebOptimizer.Core/Asset.cs
Fixes #136, fixes #199. See also discussion in #118.
As suggested [here](https://github.com/ligershark/WebOptimizer/pull/118#issuecomment-854477942), this change checks whether the source file glob has a `'/'` prefix and if so, prepends it to the files matched in `ExpandGlob`.
Given this setup:
```csharp
pipeline.AddCssBundle("/css/bundle.css", "css/*.css", "/morecss/**/*.css");
```
Current markup (paths are always relative):
```html
<link href="css/a.css" rel="stylesheet">
<link href="css/b.css" rel="stylesheet">
<link href="morecss/c.css" rel="stylesheet">
<link href="morecss/foo/d.css" rel="stylesheet">
```
Markup with this change (paths follow the source pattern):
```html
<link href="css/a.css" rel="stylesheet">
<link href="css/b.css" rel="stylesheet">
<link href="/morecss/c.css" …
```
> Make glob expansion respect rooted paths

- src/WebOptimizer.Core/AssetPipeline.cs
- test/WebOptimizer.Core.Test/AssetPipelineTest.cs
Here #141 was introduced concurrent registering of assets, so this check is no longer needed. And this is throwing an unnecessary exception at the moment.
https://github.com/nopSolutions/nopCommerce/issues/5994
> Removed unnecessary check

- src/WebOptimizer.Core/Asset.cs
- src/WebOptimizer.Core/IAsset.cs
- src/WebOptimizer.Core/TagHelpersDynamic/Helpers.cs
- test/WebOptimizer.Core.Test/AssetBuilderTest.cs
- test/WebOptimizer.Core.Test/Processors/CssMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/HtmlMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/JavaScriptMinifierTest.cs
Sometimes we need to add files to the bundle at runtime (e.g., by a condition in Razor markup). At now, if we're trying to add a file, the bundle won't be updated until the clear cache.
> Added API to append sources to the asset at runtime.

- sample/Plugins/SassCompiler.cs
- src/WebOptimizer.Core/Asset.cs
- src/WebOptimizer.Core/AssetBuilder.cs
- src/WebOptimizer.Core/IAsset.cs
- src/WebOptimizer.Core/Processors/IProcessor.cs
- src/WebOptimizer.Core/Processors/Processor.cs
- src/WebOptimizer.Core/TagHelpersDynamic/Helpers.cs
- src/WebOptimizer.Core/Taghelpers/BaseTagHelper.cs
- test/WebOptimizer.Core.Test/AssetBuilderTest.cs
- test/WebOptimizer.Core.Test/AssetMiddlewareTest.cs
- test/WebOptimizer.Core.Test/AssetTest.cs
- test/WebOptimizer.Core.Test/Processors/CssFinterprinterTest.cs
- test/WebOptimizer.Core.Test/Processors/CssMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/HtmlMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/JavaScriptMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/RelativePathAdjusterTest.cs
When using assets which are generically matched, such as **/*.scss, the processor associated with this asset is used for all matching assets. This means the asset stored in the processor is the generic one.
Because the asset in the processor is the generic one, the processor is unable to know specific details about the non-generic asset. Passing these values down the chain allows the processor to access this asset-specific information in a generic context.
Other files affected by this change have been updated to reflect it.
---
The contents of this PR are a prerequisite fix for fixing this issue: https://github.com/ligershark/WebOptimizer.Sass/issues/34
The issue there has been resolved in my fork of that project: https://github.com/alexhorner/WebOptimizer.Sass/tree/GlobalCompilerFix
This …
> Pass the AssetConfig and required components down

- src/WebOptimizer.Core/Extensions/ServiceExtensions.cs
Sets defaults on the CssBundlingSettings and CodeBundlingSettings, both of which are used by the MinifyonDemand tag helper.  Two of the 3 setup methods in ServiceExtensions do not set the values of these properties which can lead to null reference exceptions when using the MinifyOnDemand tag helper.
> #215 set defaults for CssBundlingSettings and CodeBundlingSettings

- src/WebOptimizer.Core/Taghelpers/BaseTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
When the application has a PathBase (e.g. virtual application in IIS), the individual tags to source files (in debug mode) should be based on that root path.
> Use PathBase when writing individual tags

- src/WebOptimizer.Core/Asset.cs
fixes #210 
ASP.NET Core 6 changed it's default file provider to a `CompositionFileProvider` which checks if a file exists and returns a `FileNotFoundFileInfo` if it can't find the file.
This works in `net6.0` and `net5.0`
> FIX ASP.NET Core 6 default file provider

- src/WebOptimizer.Core/Processors/CssMinifier.cs
- src/WebOptimizer.Core/Processors/HtmlMinifier.cs
- src/WebOptimizer.Core/Processors/JavaScriptMinifier.cs
1. Was running into an internal error in NUglify minifying a bundle which included signalr.js (cdnjs package "microsoft-signalr@6.0.1"). Strangely, in this package, signalr.js and signalr.min.js are both minified. Regardless, we should not just die when NUglify has internal errors. Instead, gracefully handle the exception and use the unminified version instead.
2. Looks like there is code in place to skip reminifying **bundles** that are already minified, but not **single files** when bundling is disabled, so I added a check for .min.js, .min.css, .min.html in the corresponding minifier classes (in addition to the ".min" check)
> Catch exceptions in js minifier and don't re-minify single files

- src/WebOptimizer.Core/Processors/JavaScriptMinifier.cs
Even when the setting MinifyCode is false the output is minified this seams to not be the correct outcome adding in this IF statement results in no changes being applied to the bundle in this processor
> Fix for always minifying JS

- README.md
- src/WebOptimizer.Core/Extensions/ServiceExtensions.cs
- src/WebOptimizer.Core/InCodeWebOptimizerConfig.cs
**Use Case** 
All our projects use the same Web Optimizer settings. To align the configurations and make sure the configuration will not be adapted, removed or changed in the productive environments of all applications, we like to have the ability to define the settings for the Web Optimizer directly when calling the AddWebOptimizer service extension. The call to the extension is encapsulated in a global nuget for all project, pre add all general js files like file download, bootstrapping etc.  
**Code Changes PR:** 
Via the AddWebOptimizer extension you can directly configure the web optimizer options: 
```
services.AddWebOptimizer(pipeline => 
{ 
pipeline.AddCssBundle("/css/bundle.css", "css/*.css"); 
pipeline.AddJavaScriptBundle("/js/bundle.js", "js/plus.js", "js/minus.js"); 
}, …
```
> Feature Request for in code configuration

- src/WebOptimizer.Core/AssetPipeline.cs
- test/WebOptimizer.Core.Test/AssetPipelineTest.cs
- test/WebOptimizer.Core.Test/Processors/CssMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/HtmlMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/JavaScriptMinifierTest.cs
In .NET 6 the value of context.Request.Path.Value appears to always have a leading "/" regardless of the reference in the html file.  An example of this is when you add a javascript bundle like:
`pipeline.AddJavaScriptBundle("Scripts/libraries.js", "Scripts/jquery.gridster.js");`
and reference it in the html file like:
`<script src="Scripts/libraries.js"></script>`
The bundle is added as an asset with the value of "Scripts/libraries.js" but the value of context.Request.Path.Value will be "/Scripts/libraries.js" resulting in no match.
This proposed change will sanitize all assets to have a leading "/" to ensure this matches.  
In my companies use of multiple javascript bundles with less compilation, this worked for us, but I'm not sure if this will mess with/break other possible routes. …
> Fix for change in .NET 6 for context.Request.Path.Value

- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
LinkTagHelper should not handle link-tag with inline-attribute and the check for the attribute is too late in the code resulting in an exception because "href"-variable becomes null:
System.NullReferenceException: Object reference not set to an instance of an object.
at WebOptimizer.Taghelpers.LinkTagHelper.Process(TagHelperContext context, TagHelperOutput output) in ...\WebOptimizer\src\WebOptimizer.Core\Taghelpers\LinkTagHelper.cs:line 51
Checking the inline-attribute earlier fixed this.
> Fix LinkTagHelper crash when renderin inline styles

- src/WebOptimizer.Core/Extensions/ServiceExtensions.cs
In the last release of ligershark/WebOptimizer, a new feature was added to configure the package directly in the source code. I tested the new release and found an issue when using the new feature.
During startup, the application crashed because of this error:
`Unhandled exception. System.ArgumentException: Implementation type cannot be 'Microsoft.Extensions.Options.IConfigureOptions`1[WebOptimizer.WebOptimizerOptions]'    for 'Microsoft.Extensions.Options.IConfigureOptions`1[WebOptimizer.WebOptimizerOptions]'. (Parameter 'descriptor')
at Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(IServiceCollection services, ServiceDescriptor descriptor)
at Microsoft.Extensions.DependencyInjection.ServiceExtensions.RegisterComponents(IService …
> Fix for: Configure with code is not working because of ArgumentException

- src/WebOptimizer.Core/Asset.cs
We have a custom implementation of `IFileProvider` that returned `null` for any call to `GetDirectoryContents`. We don't normally deal with contents of a directory, but when WebOptimizer ran into a file it couldn't find it called `provider.GetAllFiles("/")` which eventually lead to a NRE. It took a bit for me to track down what was going on. Our IFileProvider now properly returns `NotFoundDirectoryContents.Singleton` (and is also converted to enable nullable reference types), but this change could help someone in the future from running into the same problem.
> Handle implementation of IFileProvider that returns null

- src/WebOptimizer.Core/AssetMiddleware.cs
Hello, 
I encountered an issue today where my client setup their virtual folder in IIS (windows server) using our application name, let's call it ABC and suddenly the site was returning 404 when we requested the bundled JS file from WebOptimizer, the odd part was that it worked as long as URI did not use all upper-case letters when referring to the virtual folder path. 
So this worked   `/abc/ABCWebBundle.js`,  but this did **not** work  `/ABC/ABCWebBundle.js`.
After some debugging I found the issue resides in line 32 in AssetMiddleware.cs.  The use of the StartsWith() method has a couple of issues.. one is that it is case sensitive whereas URIs are generally not.  Secondly, it fails in my scenario when (and probably a rare case) that the file being served shares the same prefix as the …
> Fix to path issue when filename shares same prefix as PathBase.

- src/WebOptimizer.Core/Asset.cs
- src/WebOptimizer.Core/CompositeFileProviderExtended.cs
```cs
services.AddWebOptimizer(options =>
{
options.AddCssBundle("/css/jjmasterdata.min.css", "_content/JJMasterData.Web/css/jjmasterdata.css","_content/JJMasterData.Web/css/flatpickr/airbnb.css");
});
```
When I reference a RCL asset like this, I get the following error:
After my fix, everything works:
> Bugfix for Razor Class Library assets

- appveyor.yml
* use latest build image (VS2022) to get NET 8 SDK
* release build with ContinuousIntegrationBuild = true
> Improve Appveyor build logic

- LICENSE
- src/WebOptimizer.Core/WebOptimizer.Core.csproj
* update to use `LicenseExpression`
* use correct Apache 2.0 format in LICENSE
* add `PackageReadmeFile`
* use `PackageIcon`
Now pack completes without warnings, new LICENSE format should also show up correctly [like it does for Quartz.NET](https://github.com/quartznet/quartznet/blob/main/license.txt) (GitHub detects license as valid Apache 2.0). Basically adding a wall of text before the original you had.
> Improve package metadata

- README.md
Hello there, 
I recently wanted to use WebOptimizer for a project I work on, cache busting didn't work for me until I figured out (by debugging the library codes) that the file should be added somehow to the assets.
If this note (or at least giving a hint about  `pipeline.AddFiles()` function) was in the README it would save me a lot of time, hope it will do for the others.
> `README.md`  |  Add note about cache busting for files, `pipeline.AddFiles()`.

- src/WebOptimizer.Core/Asset.cs
In reference to https://github.com/ligershark/WebOptimizer/issues/190 , the error message is not clear about which asset it tried to load, this simply adds that to the error message
> Added message to exception to show which asset failed

- src/WebOptimizer.Core/AssetPipeline.cs
- src/WebOptimizer.Core/Extensions/ApplicationBuilderExtensions.cs
- src/WebOptimizer.Core/IAssetPipeline.cs
- src/WebOptimizer.Core/Processors/ItemContentEmitter.cs
- src/WebOptimizer.Core/Processors/JavaScriptMinifier.cs
- src/WebOptimizer.Core/Processors/JsBundleSettings.cs
- src/WebOptimizer.Core/TagHelpersDynamic/Helpers.cs
- src/WebOptimizer.Core/WebOptimizer.Core.csproj
- test/WebOptimizer.Core.Test/Processors/JavaScriptMinifierTest.cs
Enables the creation of Source Maps for Javascript Bundles.
Program.cs example:
```
services.AddWebOptimizer(pipeline =>
{
. . .	
pipeline.AddJavaScriptBundle("/js/bundle.js",
new WebOptimizer.Processors.JsSettings { GenerateSourceMap = true },
"/ui/crud/jquery-3.7.1.js", "/ui/all/bootstrap/bootstrap.bundle.js");
});
```
Generates a /js/bundle.js bundle containing jquery and bootstrap, with a sourcemap at /js/bundle.map.js
Chrome Dev Tools properly finds and loads it.
> Working Source Map emit for JavaScriptBundle

- src/WebOptimizer.Core/Taghelpers/BaseTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
- test/WebOptimizer.Core.Test/TagHelpers/LinkTagHelperTest.cs
- test/WebOptimizer.Core.Test/TagHelpers/ScriptTagHelperTest.cs
The cdnUrl option is not currently being applied via the ScriptTagHelper and LinkTagHelper. This PR looks to rectify that.
Resolves issue [#224](https://github.com/ligershark/WebOptimizer/issues/224)
> Apply cdnUrl option in ScriptTagHelper and LinkTagHelper

- src/WebOptimizer.Core/WebOptimizer.Core.csproj
#315 basically removed NET 6 support (removed netcoreapp3.1) and NET 6 is still supported. This PR re-introduces the support and also removes System.Text.Json reference as it comes in the box for NET 6 and later.
> Restore NET 6 support and remove System.Text.Json dependency

- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
- test/WebOptimizer.Core.Test/TagHelpers/LinkTagHelperTest.cs
- test/WebOptimizer.Core.Test/TagHelpers/ScriptTagHelperTest.cs
Fixes a bug I recently introduced where the tag helpers add the CDN and pathBase to absolute url's. These should not be added to absolute URLs.
Fixes issue [314](https://github.com/ligershark/WebOptimizer/issues/314)
> Taghelpers bug fix: do not add cdn or path base if url is absolute

- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
- test/WebOptimizer.Core.Test/TagHelpers/ScriptTagHelperTest.cs
The Script Tag Helper replaces the src attribute even if its value doesn't change. That will replace an HTMLString with a string. That will cause it to be re-encoded.   This fixes the issue I'm seeing. I did not look for other issues in the Link tag helper.
> Fix #329  Do not replace the attribute if  we are not changing its value

- src/WebOptimizer.Core/Taghelpers/LinkTagHelper.cs
- src/WebOptimizer.Core/Taghelpers/ScriptTagHelper.cs
- test/WebOptimizer.Core.Test/TagHelpers/LinkTagHelperTest.cs
A fix and a unit test for LinkTagHelper similar to the previous one for ScriptTagHelper.
> Fix #332. Prevent converting HTMLString to string to prevent double encoding &amp;

- src/WebOptimizer.Core/WebOptimizer.Core.csproj
**Description**
This pull request updates **NUglify** nuget package to latest version 1.21.15. 
The new version adds support for the CSS minification with clamp function and the "+" operator, along with other improvements and corrections.
**Related Issue**
Fixes issue #337.
**Related Issue on NUglify**
Fixes issue https://github.com/trullock/NUglify/issues/424 (fixed).
**Testing**
All existing css related tests passed
> Update NUglify package version to 1.21.15 (latest) - fix #337

- src/WebOptimizer.Core/Extensions/LoggerExtensions.cs
When a file is not found via user request, it should be an Information-level log message (e.g., stale static content that has been deleted from a high traffic website)
Fixes #336
> File Not Found should be Information-level log message

- sample2/WebOptimizer.Core.Sample2/Startup.cs
- src/WebOptimizer.Core/AssetMiddleware.cs
- src/WebOptimizer.Core/HttpResponseCacheControlAccessDirective.cs
- src/WebOptimizer.Core/WebOptimizerOptions.cs
Fixes #274 and #294
@madskristensen This was an easy one, although there are no AssetMiddleware tests currently. I think the change is pretty minor but will result in a significant performance improvement for many users. If you like it and would be willing to do a Major Version release, we can also set the default to be Public.
> Add cache-control public or private directives

- WebOptimizer.sln
- sample2/WebOptimizer.Core.Sample2/Startup.cs
- src/WebOptimizer.Core/Asset.cs
- src/WebOptimizer.Core/AssetBuilder.cs
- src/WebOptimizer.Core/AssetPipeline.cs
- src/WebOptimizer.Core/AssetResponseStore.cs
- src/WebOptimizer.Core/Extensions/CodeBundlingSettings.cs
- src/WebOptimizer.Core/Extensions/CssBundlingSettings.cs
- src/WebOptimizer.Core/Extensions/LoggerExtensions.cs
- src/WebOptimizer.Core/Extensions/ServiceExtensions.cs
- src/WebOptimizer.Core/Processors/CssFingerprinter.cs
- src/WebOptimizer.Core/Processors/CssImageInliner.cs
- src/WebOptimizer.Core/Processors/RelativePathAdjuster.cs
- src/WebOptimizer.Core/Taghelpers/ScriptInlineSrcTagHelper.cs
- src/WebOptimizer.Core/Utils/UrlPathUtils.cs
- test/WebOptimizer.Core.Test/AssetBuilderTest.cs
- test/WebOptimizer.Core.Test/AssetContextTest.cs
- test/WebOptimizer.Core.Test/AssetPipelineTest.cs
- test/WebOptimizer.Core.Test/AssetTest.cs
- test/WebOptimizer.Core.Test/Processors/ConcatenatorTest.cs
- test/WebOptimizer.Core.Test/Processors/CssMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/HtmlMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/JavaScriptMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/UseContentRootTest.cs
- test/WebOptimizer.Core.Test/TagHelpers/LinkTagHelperTest.cs
- test/WebOptimizer.Core.Test/TagHelpers/ScriptTagHelperTest.cs
1. Use CSharp collection initializer `[]` where possible
2. Use `Array.Empty<string>()` instead of `new string[0]` to avoid unnecessary allocations
3. Use `Assert.Single` and `Assert.Empty` where possible to improve error reporting in case test cases ever break
4. Remove unused `using` namespace statements
5. Use `(_, _)` for unused parameters in tests that require lambda functions e.g. TagHelperOutput tests
6. Add `readonly` access modifier where appropriate for private members that do not ever mutate state, thus enforcing immutable contracts
7. Use `new()` instead of `new TypeName()` to simplify constructor calls
8. Update Visual Studio sln file to use v17.x - I did not upgrade to slnx since it's not fully ready for prime time yet. Once it is, I will submit a PR to address. I think for …
> Update xunit tests to use appropriate style (Fixes #353)

- README.md
One code block was missing the language setting, so it didn't have any highlighting.
> README: Fix missing code-block highlighting

- README.md
The Tag Helper example code was using `text` as the language, so no highlighting was applied lol. I changed it to `cshtml`.
> README: Tag Helper example code highlighting
