- src/WebOptimizer.Core/Processors/CssFingerprinter.cs
> fix for multiple fingerprint on same content

- README.md
Also, what does it take to get the Nuget package updated?
> Missed a comma.

- src/WebOptimizer.Core/Asset.cs
I have fixed globbing broken in #82. Both example projects works.
> Fix globbing

- src/WebOptimizer.Core/Processors/Concatenator.cs
- src/WebOptimizer.Core/Processors/CssMinifier.cs
- src/WebOptimizer.Core/Processors/HtmlMinifier.cs
- src/WebOptimizer.Core/Processors/JavaScriptMinifier.cs
Fixes these situations:
- If the first file in the bundle is already minified, the minified bundle will result in empty result (404)
- If the first file in the bundle is already minified the rest of the files will not be minified in the bundle.
> Fixes two bugs when handling already minified files

- src/WebOptimizer.Core/Asset.cs
- src/WebOptimizer.Core/IAsset.cs
I'm not really sure how this should be implemented, but the feature is needed.
> Added the ability to exclude files from the asset

- src/WebOptimizer.Core/Asset.cs
- src/WebOptimizer.Core/IAsset.cs
This PR helps to avoid the exception when we handle the scenario with an empty bundle. Introduced in #183
> Fixed empty bundle handling exception

- src/WebOptimizer.Core/WebOptimizer.Core.csproj
should resolve some issue when minifying some new js construct
> update NUglify 1.13.10 to 1.16.1

- src/WebOptimizer.Core/Extensions/TagHelperExtensions.cs
- src/WebOptimizer.Core/TagHelpersDynamic/Helpers.cs
- src/WebOptimizer.Core/TagHelpersDynamic/LinkTagHelper.cs
- src/WebOptimizer.Core/TagHelpersDynamic/ScriptTagHelper.cs
It would be great If third-party developers could use this API in custom tag helpers.
> Added API for handling the output of tag helper

- src/WebOptimizer.Core/Asset.cs
Extends the usage for virtual file providers.
**Example use case:**
Bundling of generated or files outside of the local file system.
> Use IFileProvider for directory search through.

- src/WebOptimizer.Core/AssetMiddleware.cs
> Always use immutable directive for cached assets

- src/WebOptimizer.Core/WebOptimizer.Core.csproj
> Fix `<PackageLicenseUrl>` path

- src/WebOptimizer.Core/WebOptimizer.Core.csproj
Resolves https://github.com/ligershark/WebOptimizer/issues/279
> #279 upgraded NUglify

- src/WebOptimizer.Core/Build/LigerShark.WebOptimizer.Core.targets
Fixes #284
Additional info: [Item batching on self-referencing metadata](https://aka.ms/msbuild/metadata-self-ref)
> Fix MSB4120 warnings

- src/WebOptimizer.Core/WebOptimizer.Core.csproj
> #305 Add in net 5 so STJ can be externalised

- WebOptimizer.Core.Mvc3/WebOptimizer.Core.Mvc3.csproj
- WebOptimizer.sln
- sample/WebOptimizer.Core.Sample.csproj
- sample2/WebOptimizer.Core.Sample2.Lib/WebOptimizer.Core.Sample2.Lib.csproj
- sample2/WebOptimizer.Core.Sample2/WebOptimizer.Core.Sample2.csproj
- src/WebOptimizer.Core/WebOptimizer.Core.csproj
- test/WebOptimizer.Core.Test/WebOptimizer.Core.Test.csproj
- Upgrade Dotnet to Version 8 LTS
- Upgrade All NuGet packages to Latest Version available
The Upgraded version makes this faster and more compatible to projects with latest dotnet version.
> Upgrade Dotnet and Nugets

- WebOptimizer.Core.Mvc3/wwwroot/css/test/a.css
- src/WebOptimizer.Core/Processors/CssFingerprinter.cs
- src/WebOptimizer.Core/Processors/CssImageInliner.cs
- src/WebOptimizer.Core/Processors/CssMinifier.cs
- src/WebOptimizer.Core/Processors/RelativePathAdjuster.cs
- src/WebOptimizer.Core/Utils/UrlPathUtils.cs
- test/WebOptimizer.Core.Test/Mocks/MockFileInfo.cs
- test/WebOptimizer.Core.Test/Processors/ConcatenatorTest.cs
- test/WebOptimizer.Core.Test/Processors/CssFinterprinterTest.cs
- test/WebOptimizer.Core.Test/Processors/CssImageInlinerTest.cs
- test/WebOptimizer.Core.Test/Processors/EnforceFileExtensionsTest.cs
- test/WebOptimizer.Core.Test/Processors/RelativePathAdjusterTest.cs
- test/WebOptimizer.Core.Test/Utils/UrlPathUtilsTest.cs
* Extended tests of Processors
* Added support for ASP.Net Core Applications in IIS subfolders to Processors
Should fix #253, #249, #172, #153
> * Reworked Processors to not use physical file access, instead only use IFileProvider

- README.md
Documents #311 - Fully resolves/fixes #179
> Add documentation for GenerateSourceMaps feature

- test/WebOptimizer.Core.Test/Processors/CssImageInlinerTest.cs
> Remove duplicate theory InlineData

- src/WebOptimizer.Core/Asset.cs
- src/WebOptimizer.Core/AssetPipeline.cs
- src/WebOptimizer.Core/Extensions/LoggerExtensions.cs
- src/WebOptimizer.Core/Extensions/ServiceExtensions.cs
- src/WebOptimizer.Core/IAsset.cs
- test/WebOptimizer.Core.Test/AssetBuilderTest.cs
- test/WebOptimizer.Core.Test/AssetContextTest.cs
- test/WebOptimizer.Core.Test/AssetPipelineTest.cs
- test/WebOptimizer.Core.Test/AssetTest.cs
- test/WebOptimizer.Core.Test/Processors/ConcatenatorTest.cs
- test/WebOptimizer.Core.Test/Processors/CssMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/HtmlMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/JavaScriptMinifierTest.cs
- test/WebOptimizer.Core.Test/Processors/UseContentRootTest.cs
- test/WebOptimizer.Core.Test/TagHelpers/LinkTagHelperTest.cs
- test/WebOptimizer.Core.Test/TagHelpers/ScriptTagHelperTest.cs
Fixes 
#319 - see my comment at the bottom of the thread, here: https://github.com/ligershark/WebOptimizer/issues/319#issuecomment-2941375728
> Assets respect underlying source files order

- src/WebOptimizer.Core/WebOptimizer.Core.csproj
> Drop support for net6.0 TargetFramework for WebOptimizer.Core Fixes #357

- src/WebOptimizer.Core/Processors/CssFingerprinter.cs
- src/WebOptimizer.Core/Processors/CssImageInliner.cs
- src/WebOptimizer.Core/WebOptimizer.Core.csproj
Fixes #356 
Pre-requisite PR: #358
> Optimize regex via generated regex

- src/WebOptimizer.Core/Processors/Concatenator.cs
- src/WebOptimizer.Core/Processors/RelativePathAdjuster.cs
> Concatenator and RelativePathAdjuster now use Regex source generator
